spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meeting?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
#      当实体类发生改变的时候，同步更新你的表结构。如果你已经确定了表结构就可以设为none
      ddl-auto: none
#      在控制台输出sql语句
    show-sql: true
logging:
  level:
#    设置日志级别
    root: info
    com.sm130: debug
#    设置日志存储路径
  file: log/meeting.log
server:
  port: 8085
